[tasks.fmt]
command = "go"
args = ["fmt", "./..."]

[tasks.fmt-check]
script = '''
files="$(gofmt -l $(git ls-files '*.go'))"
test -z "$files" || { echo "$files"; exit 1; }
'''

[tasks.vet]
command = "go"
args = ["vet", "./..."]

[tasks.test]
command = "go"
args = ["test", "-race", "./..."]

[tasks.test-config]
command = "go"
args = ["test", "./internal/adapter/config", "-v"]

[tasks.test-chatwork]
command = "go"
args = ["test", "./internal/adapter/chatwork", "-v"]

[tasks.test-zulip]
command = "go"
args = ["test", "./internal/adapter/zulip", "-v"]

[tasks.test-slack]
command = "go"
args = ["test", "./internal/adapter/slack", "-v"]

[tasks.test-cli]
command = "go"
args = ["test", "./internal/presentation/cli", "-v"]

[tasks.cli-help]
command = "go"
args = ["run", "./cmd/synr", "--help"]

[tasks.tidy]
command = "go"
args = ["mod", "tidy"]

[tasks.build]
command = "go"
args = ["build", "./..."]

[tasks.vuln]
command = "go"
args = ["run", "golang.org/x/vuln/cmd/govulncheck@v1.1.4", "./..."]

[tasks.check]
dependencies = ["fmt-check", "vet", "test", "build", "vuln"]
