name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: 1.27.x
      - name: Install cargo-make
        run: cargo install --locked cargo-make --version 0.37.24
      - name: Check
        run: makers check
